/**
 * 定义应用路由
 */
import React from 'react';
import {
  Router,
  // browserHistory,
  hashHistory,
} from 'react-router';

// 路由配置规则参考： https://github.com/ReactTraining/react-router/blob/v3/docs/guides/RouteConfiguration.md#configuration-with-plain-routes
// 一下部分是由 ICE 相关工具自动生成的路由，请勿随意改变，否则可能会出现一些异常情况
// <!-- auto generated routes start -->
import Activitystatus from './pages/Activitystatus';
import BranchInfo from './pages/BranchInfo';
import ResetPassword from './pages/ResetPassword';
import ExperienceList from './pages/ExperienceList';
import SelfActivityInfo from './pages/SelfActivityInfo';
import SelfValidateList from './pages/SelfValidateList';
import VerifyActivity from './pages/VerifyActivity';
import VerifyActivityList from './pages/VerifyActivityList';
import CreateAdmin from './pages/CreateAdmin';
import AdminList from './pages/AdminList';
import Uplist from './pages/Uplist';
import EditActivity from './pages/EditActivity';
import Login from './pages/Login';
import VerifyList from './pages/VerifyList';
import UserList from './pages/UserList';
import ActivityList from './pages/ActivityList';
import CreateActivity from './pages/CreateActivity';
import BlankLayout from './layouts/BlankLayout';
import HeaderAsideFooterLayout from './layouts/HeaderAsideFooterLayout';
import Home from './pages/Home';
import HeaderAsideFooterResponsiveLayout from './layouts/HeaderAsideFooterResponsiveLayout';
import NotFound from './pages/NotFound';
const autoGeneratedRoutes = [{
  path: 'activity/activitystatus',
  childRoutes: [],
  component: HeaderAsideFooterLayout,
  indexRoute: {
    component: Activitystatus
  }
}, {
  path: 'activity/experiencelist',
  childRoutes: [],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: ExperienceList
  }
}, {
  path: 'branchInfo',
  childRoutes: [],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: BranchInfo
  }
}, {
  path: 'resetpassword',
  childRoutes: [],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: ResetPassword
  }
}, {
  path: 'self/info',
  childRoutes: [],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: SelfActivityInfo
  }
}, {
  path: 'self/list',
  childRoutes: [],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: SelfValidateList
  }
}, {
  path: 'admin/verifyactivity',
  childRoutes: [],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: VerifyActivity
  }
}, {
  path: 'admin/verifyactivitylist',
  childRoutes: [],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: VerifyActivityList
  }
}, {
  path: 'admin/createAdmin',
  childRoutes: [],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: CreateAdmin
  }
}, {
  path: 'admin/adminlist',
  childRoutes: [],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: AdminList
  }
}, {
  path: 'admin/adminList',
  childRoutes: [],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: AdminList
  }
}, {
  path: 'user/uplist',
  childRoutes: [],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: Uplist
  }
}, {
  path: 'activity/editActivity',
  childRoutes: [],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: EditActivity
  }
}, {
  path: 'login',
  childRoutes: [],
  component: BlankLayout,
  indexRoute: {
    component: Login
  }
}, {
  path: 'user/verifylist',
  childRoutes: [],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: VerifyList
  }
}, {
  path: 'user/userlist',
  childRoutes: [],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: UserList
  }
}, {
  path: 'activity/activitylist',
  childRoutes: [],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: ActivityList
  }
}, {
  path: 'activity/createactivity',
  childRoutes: [],
  component: HeaderAsideFooterResponsiveLayout,
  indexRoute: {
    component: CreateActivity
  }
}, {
  path: '/',
  childRoutes: [{
    path: '*',
    childRoutes: [],
    component: NotFound
  }]
}];
// <!-- auto generated routes end -->

// 自定义路由，如果 path 相同则会覆盖自动生成部分的路由配置
const customRoutes = [];

export default (
  <Router
    history={hashHistory}
    routes={[...autoGeneratedRoutes, ...customRoutes]}
  />
);
